# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PL0_Compiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1354, 625)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(219, 238, 255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.sourceCodeEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sourceCodeEdit.setGeometry(QtCore.QRect(50, 110, 631, 471))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.sourceCodeEdit.setFont(font)
        self.sourceCodeEdit.setObjectName("sourceCodeEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #196883\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(740, 110, 581, 371))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.output.setFont(font)
        self.output.setObjectName("output")
        self.sourceCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.sourceCodeLabel.setGeometry(QtCore.QRect(270, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.sourceCodeLabel.setFont(font)
        self.sourceCodeLabel.setStyleSheet("QLabel{\n"
"    color: #196883\n"
"}")
        self.sourceCodeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceCodeLabel.setObjectName("sourceCodeLabel")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(950, 60, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.outputLabel.setFont(font)
        self.outputLabel.setStyleSheet("QLabel{\n"
"    color: #196883\n"
"}")
        self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.compileButton = QtWidgets.QPushButton(self.centralwidget)
        self.compileButton.setGeometry(QtCore.QRect(910, 510, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.compileButton.setFont(font)
        self.compileButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #196883;\n"
"}")
        self.compileButton.setObjectName("compileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1354, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PL0 Compiler v1.0"))
        self.label.setText(_translate("MainWindow", "PL0_Compiler v1.0"))
        self.sourceCodeLabel.setText(_translate("MainWindow", "source code"))
        self.outputLabel.setText(_translate("MainWindow", "output"))
        self.compileButton.setText(_translate("MainWindow", "compile"))
